# author: TGibson
# creation date: 2025-08-26
# CloudFormation YAML Template
# job title: rds-aurora
AWSTemplateFormatVersion: "2010-09-09"
    Description: RDS/Aurora skeleton (off by default).
    Parameters:
  Environment:
    Type: String
    AllowedValues: [dev, test, stage, prod]
    Default: dev
    Description: Deployment environment.
  ProjectName:
    Type: String
    Default: CorePlatform
    AllowedPattern: '^[a-zA-Z0-9\-]{1,32}$'
    Description: Project short code (letters/digits/hyphen).
  Owner:
    Type: String
    Default: tgibson@omgroup.example
    Description: Service owner (email or team).
  CostCenter:
    Type: String
    Default: CC-0000
    AllowedPattern: '^[A-Za-z0-9\-]{1,32}$'
    Description: Cost center or charge code.
  DataClassification:
    Type: String
    Default: Internal
    AllowedValues: [Public, Internal, Confidential, Restricted]
    Description: Data classification level.
Parameters:
      SubnetIds:
        Type: List<AWS::EC2::Subnet::Id>
      CreateAurora:
        Type: String
        AllowedValues: ["true","false"]
        Default: "false"

    Conditions:
      DoAurora: !Equals [!Ref CreateAurora, "true"]

    Resources:
    RdsAurora:
  Type: AWS::Logs::LogGroup
  Properties:
    LogGroupName: !Sub "/${ProjectName}/${Environment}/RdsAurora"
    RetentionInDays: 30
    Tags:
      - Key: Project       ; Value: !Ref ProjectName
      - Key: Environment   ; Value: !Ref Environment
      - Key: Owner         ; Value: !Ref Owner
      - Key: CostCenter    ; Value: !Ref CostCenter
      - Key: DataClass     ; Value: !Ref DataClassification
      - Key: Author        ; Value: "TGibson"


      DbSubnets:
        Type: AWS::RDS::DBSubnetGroup
        Properties:
          DBSubnetGroupDescription: "App DB subnets"
          SubnetIds: !Ref SubnetIds

      AuroraCluster:
        Condition: DoAurora
        Type: AWS::RDS::DBCluster
        Properties:
          Engine: aurora-mysql
          EngineMode: provisioned
          DBSubnetGroupName: !Ref DbSubnets
          DeletionProtection: true
          StorageEncrypted: true
